### ISSUE TITLE
Infinite Loading Animation Replaces Hidden Friend Suggestions

### ISSUE THREAD

**Issue by suryadip2008** [bocajthomas/SE-Extended#100]
### Description

**Context**

Latest version of Snapchat introduces "Simple Snapchat" feature
Simplifies interface into three tab view
Moves stories to the chat page at the top

**Issue Description**

User has enabled "hide story suggestions >hide friend suggestions & hide suggested friend stories" in SE Extended
Friend suggestions are successfully hidden, but an infinite loading animation appears in their place
This loading animation defeats the purpose of hiding the friend suggestions
The space where friend suggestions were should be completely empty
Loading animation persists even when a friend has posted a story
Infinite loading occurs beside the friend's story

**Expected Behavior**

When "hide story suggestions >hide friend suggestions & hide suggested friend stories" is enabled, the space for friend suggestions should be completely empty, with no loading animation or other UI elements.

**Actual Behavior**

Friend suggestions are hidden as intended
However, an infinite loading animation appears in place of the hidden suggestions
The loading animation persists indefinitely
Issue occurs even when friends' stories are present

**Additional Notes**

This behavior conflicts with the intended functionality of the "hide story suggestions" feature in SE Extended. While it successfully hides the friend suggestions, the presence of the loading animation negates the desired clean, uncluttered user interface.

https://github.com/bocajthomas/SE-Extended/assets/137927782/ce8e892d-db27-4013-9f02-77796cb5bb2c

![photo_6330151619978706923_y](https://github.com/bocajthomas/SE-Extended/assets/137927782/9b01bd99-d421-4c7b-acd6-963a52fa204e)

### Reproduction steps

1. Ensure you are using the latest version of Snapchat with the "Simple Snapchat" feature on
2. In SE Extended settings, navigate to "hide story suggestions "
3. Enable the option to hide friend suggestions & hide suggested friend stories
4. Open Snapchat and go to the chat page (where stories are now located at the top)
5. Observe the area where friend suggestions would normally appear
6. Note the presence of an infinite loading animation in this area
7. Wait for a friend to post a story or find a friend who has an active story
8. Observe that the loading animation persists even next to active friend stories

### Snapchat Version

12.93.0.41

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Please use stable version of Snapchat.

**Comment by suryadip2008** [comment]
> Please use stable version of Snapchat

Tested on stable version too.

**Comment by bocajthomas** [comment]
> Tested on stable version too.

The `simple snapchat` is a beta feature for snapchat plus.
this is only found in betas or if you turn on `Hidden Snapchat Plus Features` 

i am not fixing this!

**Comment by suryadip2008** [comment]
> > Tested on stable version too.
> 
> The `simple snapchat` is a beta feature for snapchat plus. this is only found in betas or if you turn on `Hidden Snapchat Plus Features`
> 
> i am not fixing this!

This issue might have been fixed. https://github.com/bocajthomas/SE-Extended/commit/f461a0fb2c3812c6e262dcfba9f1d14ea2a122bf

Tested on latest beta version of Snapchat.
