### ISSUE TITLE
Infinite Log In

### ISSUE THREAD

**Issue by 5h4d0wIxI** [bocajthomas/SE-Extended#118]
### Description

I was using the acc switch feature to log in to my second account, even tho all my credentials are correct it doesn't let me log in, it just keeps loading instead. 
![Screenshot_20240808-184635_Snapchat](https://github.com/user-attachments/assets/454bec50-0181-4a77-86cc-f2c675e1dcd0)

### Reproduction steps

1. Open account switcher
2. Click on "Log out"
3. Press "switch account" (the one already on snapchat, not the up left one)
4. Enter your user and pass
5. Press "Log in"
6. It should keep logging in infinitely.

### Logs

No logs 

### Snapchat Version

13.1.0.43

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by suryadip2008** [comment]
> ### Description
> I was using the acc switch feature to log in to my second account, even tho all my credentials are correct it doesn't let me log in, it just keeps loading instead. ![Screenshot_20240808-184635_Snapchat](https://private-user-images.githubusercontent.com/172432457/356312603-454bec50-0181-4a77-86cc-f2c675e1dcd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzY3ODQsIm5iZiI6MTcyMzEzNjQ4NCwicGF0aCI6Ii8xNzI0MzI0NTcvMzU2MzEyNjAzLTQ1NGJlYzUwLTAxODEtNGE3Ny04NmNjLWYyYzY3NWUxZGNkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzAxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTMwYzIxNzViZmNkNjYwY2Y1MjAwNmEyOTQ5NDlhYjQxOTI4OWQ5YTEwZjRkY2NkYWNiODVlMDhlZWNkY2Y4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yL15GdRe_YuQWaskLlfnrCv5T_bb5SgXWfpmnMrBMXk)
> 
> ### Reproduction steps
> 1. Open account switcher
> 2. Click on "Log out"
> 3. Press "switch account" (the one already on snapchat, not the up left one)
> 4. Enter your user and pass
> 5. Press "Log in"
> 6. It should keep logging in infinitely.
> 
> ### Logs
> No logs
> 
> ### Snapchat Version
> 13.1.0.43
> 
> ### SE Extended Version
> 1.0.0
> 
> ### Agreement
> * [x]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [ ]  I have attached a log if deemed necessary.
> * [x]  This issue is not a duplicate.

Please disable Security Features in SE Extended Settings.

**Comment by 5h4d0wIxI** [comment]
> > ### Description
> > I was using the acc switch feature to log in to my second account, even tho all my credentials are correct it doesn't let me log in, it just keeps loading instead. ![Screenshot_20240808-184635_Snapchat](https://private-user-images.githubusercontent.com/172432457/356312603-454bec50-0181-4a77-86cc-f2c675e1dcd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzY3ODQsIm5iZiI6MTcyMzEzNjQ4NCwicGF0aCI6Ii8xNzI0MzI0NTcvMzU2MzEyNjAzLTQ1NGJlYzUwLTAxODEtNGE3Ny04NmNjLWYyYzY3NWUxZGNkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzAxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTMwYzIxNzViZmNkNjYwY2Y1MjAwNmEyOTQ5NDlhYjQxOTI4OWQ5YTEwZjRkY2NkYWNiODVlMDhlZWNkY2Y4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yL15GdRe_YuQWaskLlfnrCv5T_bb5SgXWfpmnMrBMXk)
> > 
> > ### Reproduction steps
> > 1. Open account switcher
> > 2. Click on "Log out"
> > 3. Press "switch account" (the one already on snapchat, not the up left one)
> > 4. Enter your user and pass
> > 5. Press "Log in"
> > 6. It should keep logging in infinitely.
> > 
> > ### Logs
> > No logs
> > 
> > ### Snapchat Version
> > 13.1.0.43
> > 
> > ### SE Extended Version
> > 1.0.0
> > 
> > ### Agreement
> > * [x]  This is not a bug regarding Snapchat+.
> > * [x]  I have provided a detailed description of the issue.
> > * [ ]  I have attached a log if deemed necessary.
> > * [x]  This issue is not a duplicate.
> 
> Please disable Security Features in SE Extended Settings.

ohh thank you so much bro
