### ISSUE TITLE
Pre Patched APKs do not work on Android 15 (non root)...

### ISSUE THREAD

**Issue by thelolinator2000** [bocajthomas/SE-Extended#119]
### Description

Once the pre patched APK is installed on Android 15, it will show a successful install popup as usual however when opening the patched Snapchat application it does not open and instantly crashes (non root)

### Reproduction steps

1. Install the Pre Patched APK on Android 15
2. Open the app
3. It will crash instantly 

### Snapchat Version

13.3.0.42

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
This is because the official LSPatch app is android 9 to 14 ( LSPatch 402 ) 

A15 is being tested via this fork 
https://github.com/JingMatrix/LSPatch
