### ISSUE TITLE
New Cool Possible Feature

### ISSUE THREAD

**Issue by Brandon425-ops** [bocajthomas/SE-Extended#123]
### Description

Hey so idk if this is possible but I think it would be cool to add a feature where you can locally edit people's messages where on your side you can see the edited text but on their side it's normal. But add an extra option where like if you edit someones message you can toggle on show (Edited) next to it or to choose not to show that if that is not possible then either let the feature automatically have the (Edited) text right next to it or just not have the (Edited) right next to it

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
Unfortunately I can't do that because I can't ensure backwards compatibility of this kind of feature across a wide range of versions
