### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by YashSoPro** [bocajthomas/SE-Extended#136]
### Description

when i put my login details it just loads forver im using lspatch

### Reproduction steps

open snapchat
login
see error

### Logs

what log?

### Snapchat Version

3.1.0.43

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Disable security features.

1. Head to the `home` tab
2. Tap the settings icon 
3. Scroll down 
4. Toggle on `disable security features`

**Comment by YashSoPro** [comment]
> Disable security features.
> 
> 1. Head to the `home` tab
> 2. Tap the settings icon
> 3. Scroll down
> 4. Toggle on `disable security features`

nope like when i install snapchat with module open it i see login interface i put my email id my password and click login button and it loads forever and whilrle doing setup of module like language etc i already disabled security features
