### ISSUE TITLE
SnapChat Crashing / Won't Open

### ISSUE THREAD

**Issue by lunarorg** [bocajthomas/SE-Extended#138]
### Description

I used to use SnapEnhance 2.1.0 debug. Everything was working fine and then one day, I tried opening SnapChat and it just closed immediately. Not even SnapChats processes would start (that I could see in Dev options anyway).

I tried swapping over to SE Extended but SnapChat did the exact same thing. The stock SnapChat application as well as a few other mods work however (FMSnap and hard-modded APK's). I've tried patching with both the SE Extended manager AND the core APK. None will work.

My device is a Samsung Galaxy S20 FE 5G running Android 14 (OneUI 6.1). My SnapChat version is 12.81.0.44. I've tried using the SIF and mod version check settings but that didn't help. Also tried clearing SnapChat and SE Extended cache / storage too. Any suggestions are much appreciated!

PS: I'm using the latest Shizuku and LS-Patch builds, hopefully it's not them that's the issue. Although, I have a Shizuku branch linked in Wireless Debugging and can't "Forget" it. Not sure if that has something to do with it but it's worth notice.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See Error.

### Snapchat Version

12.81.0.44

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
no logs

**Comment by lunarorg** [comment]
> no logs

I didn't include any because they won't show. I go into that section and it's just blank.
