### ISSUE TITLE
...Core or debug??

### ISSUE THREAD

**Issue by idontveapc** [bocajthomas/SE-Extended#139]
### Description

The latest core build crashes, which one is used?

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See Error.

### Snapchat Version

13.14.0.45

### SE Extended Version

1.0.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
https://github.com/bocajthomas/SE-Extended/wiki/Installation-Guide
