### ISSUE TITLE
Crash with native hooks

### ISSUE THREAD

**Issue by oli532** [bocajthomas/SE-Extended#142]
### Description

When i enable native hooks when i open snapchat and click on my pfp i receive a black screen and then it crashes
![Screenshot_20241110_211951_me_rhunk_snapenhance_MainActivity](https://github.com/user-attachments/assets/b424fcd9-515a-4cf3-9e7b-c8e5784b8282)
 This is the error 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See Error.

### Logs

[SE Extended-logs-1731273811545.zip](https://github.com/user-attachments/files/17693103/SE.Extended-logs-1731273811545.zip)

### Snapchat Version

12.50.1.0

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by oli532** [comment]
Wdym not planned??

**Comment by bocajthomas** [comment]
use [v12.81.0.44](https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-12-81-0-44-release/snapchat-12-81-0-44-2-android-apk-download/)

**Comment by oli532** [comment]
Is it not possible to use this version for the multi snap feature?
