### ISSUE TITLE
Infinate logging in

### ISSUE THREAD

**Issue by cbritten09** [bocajthomas/SE-Extended#143]
### Description

When I log in after installing both the SE Extended apk and the Prepatch apk and try to log in it gets stuck on the logging in message

I have seen another issue like this but I have security features turned off
![Screenshot_20241113_074723_Snapchat](https://github.com/user-attachments/assets/8c353b17-96c7-4913-8c77-96d780169991)

### Reproduction steps

1. Install SE Extended
2. Log in
3. Says "Logging in" and stays on that screen

### Logs

[SE Extended-logs-1731485075341.zip](https://github.com/user-attachments/files/17728664/SE.Extended-logs-1731485075341.zip)

### Snapchat Version

12.81.0.44

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Disable security features

1. Head to the `Home` tab 
2. Tap the gear Icon ( ⚙️ )
3. Scroll down to the bottom 
4. Toggle on `Disable security features`

**Comment by cbritten09** [comment]
security features were already disabled and it still doesn't work

**Comment by cbritten09** [comment]
> Disable security features
> 
> 1. Head to the `Home` tab
> 2. Tap the gear Icon ( ⚙️ )
> 3. Scroll down to the bottom
> 4. Toggle on `Disable security features`

security features were already disabled and it still doesn't work

**Comment by bocajthomas** [comment]
Make sure you update SE Extended to the lastest available version 

The current hash is bf5942f ( 3 days ago )

**Comment by bocajthomas** [comment]
118
