### ISSUE TITLE
Bug when trying to initialize e2e encryption

### ISSUE THREAD

**Issue by Dantoza** [bocajthomas/SE-Extended#145]
I get the message You just received a public key request. Click below to accept it, but there is no button or anything to click on.

**Comment by bocajthomas** [comment]
Turn `End-To-End Encryption` on thats found in `Experimental` next head to the social tab and add that friend once you have added that friend click on that friend scroll to the bottom and tap import base 64

**Comment by FlipperFlopper99** [comment]
> Turn `End-To-End Encryption` on thats found in `Experimental` next head to the social tab and add that friend once you have added that friend click on that friend scroll to the bottom and tap import base 64
> 
> Also toggle on Use E2E Encryption on that friend

Not sure what you mean. What do you import?
