### ISSUE TITLE
Friend Feed Bug

### ISSUE THREAD

**Issue by Quasar-IO** [bocajthomas/SE-Extended#147]
### Description

When holding down on a User in friend feed, the app crashes. I have no themes, scripts or features enabled.

https://github.com/user-attachments/assets/4089ff27-4065-4449-a4b7-c17f35dc290e

### Reproduction steps

1. Open SnapChat
2. Hold on a User in Friend Feed
3. App crashes

### Logs

[SE Extended-logs-1734179325614.zip](https://github.com/user-attachments/files/18135777/SE.Extended-logs-1734179325614.zip)

### Snapchat Version

12.81.0.44

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
fixed in d2a1da8
