### ISSUE TITLE
Custom emoji fonts

### ISSUE THREAD

**Issue by BrokenOG** [bocajthomas/SE-Extended#58]
### Description

When ever i try to use custom emojis (.ttf) it shows the error and null 

### Reproduction steps

 1. Go the file imports 
 2. Click on import file 
 3. See error saying null

### Logs

[snapenhance-logs-1717294005487.zip](https://github.com/user-attachments/files/15523937/snapenhance-logs-1717294005487.zip)

### Snapchat Version

12.88.0.43

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Can you send the .ttf file

**Comment by Xa19u** [comment]
Similarly I used multiples emojis ttf file ...In SE Extended it shows Emojis file is loaded but in Snapchat app it is not implemented

**Comment by 2faryc98gn5x** [comment]
> Similarly I used multiples emojis ttf file ...In SE Extended it shows Emojis file is loaded but in Snapchat app it is not implemented

stop using this skidded EX dev fork maybe use the real one https://github.com/rhunk/SnapEnhance just look at this guys commits nothing good just stolen https://github.com/bocajthomas/SE-Extended/commits/dev/


https://github.com/rhunk/SnapEnhance is the only REAL repo this guy is just stealing work

**Comment by bocajthomas** [comment]
> Similarly I used multiples emojis ttf file ...In SE Extended it shows Emojis file is loaded but in Snapchat app it is not implemented

It doesn't work just yet

**Comment by bocajthomas** [comment]
@BrokenOG put the font inside the SE Extended/SnapEnhance folder
