### ISSUE TITLE
Basic Bish 

### ISSUE THREAD

**Issue by bloatworm2** [bocajthomas/SE-Extended#63]
### Description

Name: Magical Green
Main Text Color: #FF17FF00 
Main Friend Feed Text Color: #000000 
Secondary Friend Feed Text Color: #FF17FF00 
Snaps With Sound Text Color: #FF17FF00 
Snaps Without Sound Text Color: #FF17FF00 
Background Color: #FF17FF00 
Background Surface Color: #FF17FF00 
Conversations Line Color: #000000 
Action Menu Background Color: #FF17FF00 
Action Menu Round Background Color: #FF17FF00 
Camera Gridlines Color: #000000  

### Agreement

- [X] Have you submitted This Theme correctly?

**Comment by bocajthomas** [comment]
@bloatworm2 the theme isnt changed from the example

**Comment by bloatworm2** [comment]
> @bloatworm2 the theme isnt changed from the example

Turns out im hung over.
