### ISSUE TITLE
Unable to view snap preview 

### ISSUE THREAD

**Issue by BrokenOG** [bocajthomas/SE-Extended#68]
### Description

When ever i try to preview a snap sent in chat it starts buffering nd then a text appear saying failed to create preview 

### Reproduction steps

1. Open chat with someone 
2. Hold on unseen snap nd click on preview 
3. There will be buffering for 1 2 sec then it will say failed to create preview 

### Snapchat Version

12.90.0.35 beta (was encountering problem on stable version too)

### SE Extended Version

1.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Please provide the logs

**Comment by bocajthomas** [comment]
[snapenhance-logs-1717443906390.zip](https://github.com/user-attachments/files/15539098/snapenhance-logs-1717443906390.zip)

**Comment by bocajthomas** [comment]
@BrokenOG what version of snapchat have you tried?

**Comment by BrokenOG** [comment]
> @BrokenOG what version of snapchat have you tried?

I firstly tried latest stable (available on play store) then beta version

**Comment by BrokenOG** [comment]
> @BrokenOG If you want more information, if the snap was only sent to one friend, Snapchat doesn't keep the decryption keys so you can't use the preview function. However, I've added the Convert Message Locally feature, which allows you to convert a snap into a media saved in the chat by fetching cached files, which can help if you want to review what you've sent. 
> Also if the snap was opened more than 2 days ago it may have been deleted from the servers and is therefore no longer available (if it's no longer cached).

Thanks 🫡

**Comment by bocajthomas** [comment]
> @BrokenOG If you want more information, if the snap was only sent to one friend, Snapchat doesn't keep the decryption keys so you can't use the preview function. However, I've added the Convert Message Locally feature, which allows you to convert a snap into a media saved in the chat by fetching cached files, which can help if you want to review what you've sent. Also if the snap was opened more than 2 days ago it may have been deleted from the servers and is therefore no longer available (if it's no longer cached).

@rhunk hello there ✋️

**Comment by Xa19u** [comment]
OMG what the fuck is happening here ...😂🤣
