### ISSUE TITLE
Composer View Theming

### ISSUE THREAD

**Issue by rhunk** [bocajthomas/SE-Extended#72]
### Description

Since Snapchat uses Composer to display components on multiple platforms, rendering is not handled by android views but by the native library instead. As you work a lot on graphical interfaces and I don't have the time to do it, can you make it possible to customize colors as is already possible by default, but for Composer views? (like friend profile view, snap pro menus, snapchat + settings, quick add and search for example)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
Sure

**Comment by authorisation** [comment]
Huh, looks like your comment vanished
Weird...

**Comment by bocajthomas** [comment]
> Huh, looks like your comment vanished Weird...
> 
> Anyways any updates on this? Shouldn't be too hard to do. We'd like to merge this soon.

Thought SnapEnhance development stopped for a bit. thats why i wasn't in a rush to work on it. It just has a few errors i need to fix and to link it in ether the `Colors` or `Composer Hooks` category
