### ISSUE TITLE
Midnight Slate

### ISSUE THREAD

**Issue by suryadip2008** [bocajthomas/SE-Extended#96]
### Description

Name: Midnight Slate

Main Text Color: #FFFFFF

Main Friend Feed Text Color: #FFFF00

Secondary Friend Feed Text Color: #00FFFF

Snaps With Sound Text Color: #FF9800

Snaps Without Sound Text Color: #00E676

Background Color: #1F2833

Background Surface Color: #1F2833

Conversations Line Color: #1F2833

Action Menu Background Color: #2C3E50

Action Menu Round Background Color: #34495E

Action Menu Icon Color: #FFFF00

Camera Gridlines Color: #FFFFFF

### Agreement

- [X] Have you submitted This Theme correctly?

**Comment by bocajthomas** [comment]
Added in 0b6562f
