### ISSUE TITLE
Check how long before Super BFF or BFF

### ISSUE THREAD

**Issue by brog-io** [bocajthomas/SE-Extended#99]
### Description

It'd be a really useful feature to see in how many days I become someone's Super BFF. Currently there is no way to tell.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by suryadip2008** [comment]
> ### Description
> It'd be a really useful feature to see in how many days I become someone's Super BFF. Currently there is no way to tell.
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

I'm sorry to say that feature is not yet possible as there is no way to extract how many days someone has been your super bff. This was earlier suggested as a script ideas and abandoned.

**Comment by brog-io** [comment]
> I'm sorry to say this feature is not yet possible as there is no way to extract how many days someone has been your super bff. This was earlier suggested as a script ideas and abandoned.

Alright, I thought that that might've been an issue

**Comment by BrokenOG** [comment]
> > ### Description
> > It'd be a really useful feature to see in how many days I become someone's Super BFF. Currently there is no way to tell.
> > 
> > ### Agreement
> > * [x]  There is no issue already suggesting my feature.
> 
> I'm sorry to say this feature is not yet possible as there is no way to extract how many days someone has been your super bff. This was earlier suggested as a script ideas and abandoned.

Can we do that we can see the date we are #1 with someone user can calculate days by himself/herself

**Comment by suryadip2008** [comment]
> > > ### Description
> > > It'd be a really useful feature to see in how many days I become someone's Super BFF. Currently there is no way to tell.
> > > ### Agreement
> > > 
> > > * [x]   There is no issue already suggesting my feature.
> > 
> > 
> > I'm sorry to say this feature is not yet possible as there is no way to extract how many days someone has been your super bff. This was earlier suggested as a script ideas and abandoned.
> 
> Can we do that we can see the date we are #1 with someone user can calculate days by himself/herself

Yes, that will be possible. A small prototype of the concept is already available in the telegram channel. (For now, the script only shows the default duration as a toast and will not take any user input.) https://t.me/SE_Extended_Chat/18/4754 

Will modify the script so that it can take user input for calculating the days. Will keep you updated.
